### ISSUE TITLE
custom:my-slider-v2 dependancy

### ISSUE THREAD

**Issue by slungs** [sharn25/HA-Custom_Cards#1]
Hi, fantastic work, especially a fan of the light card. In the config there is a card specified:
` type: custom:my-slider-v2`

Edit: Too tired, too quick to comment... but the above should probably be added to the requirements for the light card to work. :) (https://github.com/AnthonMS/my-cards)

**Comment by sharn25** [comment]
Added to the requirement. Thanks.
