### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by mlo-Tek** [sharn25/HA-Custom_Cards#2]
Hi,

would like to test your dashboard. Could you give me some detailed infos how to install this stuff propably? Especially the custom icons stuff? Thanks.

**Comment by ahs-nl** [comment]
For the custom icons stuff, see: #4

**Comment by sharn25** [comment]
Thanks Guys. 

Steps:
1. Copy the .js files to your configuration/www/ folder.
2. Under home assistant go to setting Dashboards > click three dots on right side and select Resources.
3. Click Add resource.
4. Under url enter: /local/js_file_name.js
5. Select JavaScript module and create.

The JS file will be added to your HA.

Regarding Cards, just copy the code from the yaml file and paste in under new manual card and change as per your requirements.
