### ISSUE TITLE
Climate card?

### ISSUE THREAD

**Issue by dnestico** [sharn25/HA-Custom_Cards#3]
Not an issue, these cards are great and Im preparing to use them all on my HA dashboard redesign. 

Just wondering do you plan to make more, specifically a climate card? Thanks.

**Comment by sharn25** [comment]
I usually do the cards as I add them to my dashboard. Climate card I dot as I don't have any smart device which require this card. No AC/Heater.

**Comment by dnestico** [comment]
Alright, thanks for the response. The cards are nice.
