### ISSUE TITLE
Install of dashboard

### ISSUE THREAD

**Issue by tunavis** [sharn25/HA-Custom_Cards#4]
Good day,

Any idee where this code shoulde be added:

  resources:
    - url: /local/custom_icon.js
      type: module?

**Comment by ahs-nl** [comment]
I had the same question myself. The solution is to download and put the file [`custom_icons.js`](https://github.com/sharn25/HA-Custom_Cards/blob/main/custom_icon.js) into your HA /www directory manually. Make sure to load the file as instructed or in the frontend directly (Edit dashboard > Manage resources > Add resource). Reload HA and the icons should render properly.

**Comment by sharn25** [comment]
Thanks Guys. 

Steps:
1. Copy the .js files to your configuration/www/ folder.
2. Under home assistant go to setting Dashboards > click three dots on right side and select Resources.
3. Click Add resource.
4. Under url enter: /local/js_file_name.js
5. Select JavaScript module and create.

The JS file will be added to your HA.

**Comment by ahs-nl** [comment]
Alternatively, it's of course an option to use default icons (or another icon library) instead, I guess.

**Comment by sharn25** [comment]
Yes, that's true.
